# Variables
@baseUrl = http://localhost:3333

# Health check
# @name healthCheck
GEt {{baseUrl}}/health

###

# Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Sala de teste",
  "description": "Essa é uma sala de teste"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# Get room  questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create question
# @name createQuestion
POST {{baseUrl}}/rooms/7026c25d-3729-4160-8757-f8b6e26641a8/questions
Content-Type: application/json

{
  "question": "O que é Vue.js e a sua diferença em realação ao Angular?"
}